### PR TITLE
Ranked pathways initial experiment

### PR DESCRIPTION
**Pull request by ajlee21**
This PR is the first pass experiment to use the VAE to simulate gene expression experiments in order to generate a null set of experiments. With this null set we can compare the pathways enriched in our template experiment vs those found in our null set to hopefully identify those pathways that are template-specific

### CODE REVIEW

**Comment by ajlee21** [comment]
Closing this PR while making additional changes

**Comment by ajlee21** [comment]
This PR is very large due to the rushed preliminary analysis.

This PR is adding a new analysis where all the notebooks can be found in `Ranked_pathways` directory.

The notebooks can be broken down into the following steps:
- `1_process_data.ipynb` downloads, processes the gene expression data and trains VAE
- `2_simulate_data.ipynb` simulates gene expression experiments (@ben-heil this notebook might be useful for you to look at if you are interested in possibly using this method for your own work).
- `3_gene_DE_analysis.ipynb` Calculating DE association statistics for each simulated experiments
- `5_analyze_generic_genes_and_pathways.ipynb` assesses the results. In particular we were interested in determining if our simulation could be used to identify "generic genes" (i.e. genes that are DE across a broad range of experiments)

I understand that this is a large PR, and the above are the main notebooks. But if you have to look at one, `5_analyze_generic_genes_and_pathways.ipynb` contains the key results we found.

**Comment by cgreene** [comment]
I wonder if this makes sense more as its own repo. Is it self contained? It looks like there is a notebook to download and train the VAE, so if it's functionally separate from the broader repo, it may make the most sense to have it separate. This would also help to refactor any code that you use from simulate-expression-compendia to be modular enough to, say, make `pip install`able, which could help others use it in their own work.

**Comment by ajlee21** [comment]
Yes that makes a lot more sense. 

This originally started as a one-off analysis that I was using the previously trained model and previously made functions. Now it has evolved into a project of its own, using a new trained model and the existing methods from this simulate-expression-compendia repository to ask different scientific question. 

Given that, I think it does makes sense to have this work be in its own repo. I'll also try to refactor the methods to make them installable. That would be very helpful!

**Pull request closed without merging**
